import { ArrowLeft, ArrowRight, CalendarDays, Check, CheckCircle2, Clock3, MapPin, ShieldAlert, Truck, UserRound, UsersRound, UtensilsCrossed } from 'lucide-react'
import { useState } from 'react'
import { drivers, events, roles, vehicles } from '../../data/mockData'
import type { Assignment, Volunteer, VolunteerTeam } from '../../types'
import { Avatar, formatDate, formatTime, Modal, StatusBadge } from '../common/UI'

type Props = { volunteers: Volunteer[]; teams: VolunteerTeam[]; assignments: Assignment[]; initialVolunteerId?: string; onClose: () => void; onCreate: (assignment: Assignment) => void; notify: (message: string, kind?: 'success' | 'error') => void }
const labels = ['Select Event', 'Volunteer / Team', 'Select Driver', 'Select Vehicle', 'Review']

export default function CreateAssignmentDialog({ volunteers, teams, assignments, initialVolunteerId, onClose, onCreate, notify }: Props) {
  const [step, setStep] = useState(0)
  const [eventId, setEventId] = useState('E001')
  const [subject, setSubject] = useState(initialVolunteerId ? `v:${initialVolunteerId}` : '')
  const [driverId, setDriverId] = useState('')
  const [vehicleId, setVehicleId] = useState('')
  const [role, setRole] = useState('Pickup Volunteer')
  const [submitting, setSubmitting] = useState(false)
  const event = events.find(item => item.eventId === eventId)!
  const volunteer = subject.startsWith('v:') ? volunteers.find(v => v.volunteerId === subject.slice(2)) : undefined
  const team = subject.startsWith('t:') ? teams.find(t => t.teamId === subject.slice(2)) : undefined
  const driver = drivers.find(d => d.driverId === driverId)
  const vehicle = vehicles.find(v => v.vehicleId === vehicleId)
  const availableTeams = teams.filter(t => t.memberIds.some(id => volunteers.find(v => v.volunteerId === id)?.status === 'AVAILABLE'))
  const availableVolunteers = volunteers.filter(v => v.status === 'AVAILABLE')
  const canNext = [!!eventId, !!subject, !!driverId, !!vehicleId, true][step]
  const goNext = () => { if (!canNext) { notify('Choose an option before continuing.', 'error'); return }; if (step === 1 && volunteer) { const conflict = assignments.some(a => a.volunteerId === volunteer.volunteerId && a.eventId === eventId && ['Pending','Accepted','In Progress'].includes(a.status)); if (conflict) { notify('Cannot assign this volunteer. Volunteer already has another assignment during this time.', 'error'); return } } setStep(step + 1) }
  const create = () => { if (!event || !driver || !vehicle || !subject) { notify('Complete each assignment step first.', 'error'); return }; setSubmitting(true); window.setTimeout(() => { const next = Math.max(0, ...assignments.map(a => Number(a.assignmentId.replace('ASG','')) || 0)) + 1; onCreate({ assignmentId:`ASG${String(next).padStart(3,'0')}`, ...(volunteer ? { volunteerId:volunteer.volunteerId } : { teamId:team!.teamId }), eventId:event.eventId, vehicleId:vehicle.vehicleId, driverId:driver.driverId, role, status:'Pending', assignedTime:new Date().toISOString() }); setSubmitting(false) }, 450) }
  return <Modal title="Create assignment" subtitle="Match a pickup with the right people and resources." onClose={onClose} wide><div className="wizard"><div className="wizard-steps">{labels.map((label,index) => <div key={label} className={`wizard-step ${index === step ? 'current' : ''} ${index < step ? 'done' : ''}`}><span>{index < step ? <Check size={14}/> : index + 1}</span><small>{label}</small></div>)}</div><div className="wizard-content">
    {step === 0 && <><div className="wizard-title"><span>STEP 01 / 05</span><h3>Select a pickup event</h3><p>Choose the food rescue requirement this assignment will support.</p></div><div className="choice-grid event-choice-grid">{events.map(item => <button key={item.eventId} className={`choice-card event-choice ${eventId === item.eventId ? 'selected' : ''}`} onClick={() => setEventId(item.eventId)}><div className="choice-card-top"><span className="choice-icon"><UtensilsCrossed size={19}/></span><span className="choice-check"><Check size={14}/></span></div><strong>{item.title}</strong><span className="event-type">{item.eventType}</span><div className="choice-meta"><span><MapPin size={15}/>{item.location}</span><span><Clock3 size={15}/>{formatDate(item.dateTime)} · {formatTime(item.dateTime)}</span></div><div className="meal-count">Approximately {item.expectedMeals} meals</div></button>)}</div></>}
    {step === 1 && <><div className="wizard-title"><span>STEP 02 / 05</span><h3>Choose your volunteers</h3><p>Select an available team or an individual volunteer for {event.title}.</p></div><div className="choice-section-heading"><UsersRound size={18}/> Available teams</div><div className="choice-grid two-col">{availableTeams.map(item => { const lead = volunteers.find(v => v.volunteerId === item.leaderId); const available = item.memberIds.filter(id => volunteers.find(v => v.volunteerId === id)?.status === 'AVAILABLE').length; return <button key={item.teamId} className={`choice-card people-choice ${subject === `t:${item.teamId}` ? 'selected' : ''}`} onClick={() => setSubject(`t:${item.teamId}`)}><div className="choice-card-top"><span className="choice-icon"><UsersRound size={19}/></span><span className="choice-check"><Check size={14}/></span></div><strong>{item.teamName}</strong><span>Leader: {lead?.name ?? 'Unassigned'}</span><small>{item.memberIds.length} members · {available} currently available</small></button> })}</div><div className="choice-section-heading"><UserRound size={18}/> Available volunteers</div><div className="choice-grid two-col">{availableVolunteers.map(item => <button key={item.volunteerId} className={`choice-card people-choice ${subject === `v:${item.volunteerId}` ? 'selected' : ''}`} onClick={() => setSubject(`v:${item.volunteerId}`)}><div className="choice-card-top"><Avatar name={item.name} size="sm"/><span className="choice-check"><Check size={14}/></span></div><strong>{item.name}</strong><span>{item.skills.slice(0,2).join(', ')}</span><small>Available for assignment</small></button>)}</div><div className="field role-field"><span>Assignment role</span><select value={role} onChange={e => setRole(e.target.value)}>{roles.map(item => <option key={item} value={item}>{item}</option>)}</select></div></>}
    {step === 2 && <><div className="wizard-title"><span>STEP 03 / 05</span><h3>Select a driver</h3><p>Only available drivers with valid licences can be selected.</p></div><div className="choice-grid two-col">{drivers.map(item => { const expired = new Date(item.licenseExpiry) < new Date(); const enabled = item.status === 'AVAILABLE' && !expired; return <button key={item.driverId} disabled={!enabled} title={!enabled ? expired ? 'Driver licence expired' : 'Driver unavailable' : undefined} className={`choice-card resource-choice ${driverId === item.driverId ? 'selected' : ''}`} onClick={() => setDriverId(item.driverId)}><div className="choice-card-top"><span className="choice-icon"><UserRound size={19}/></span><span className="choice-check"><Check size={14}/></span></div><strong>{item.name}</strong><span>{item.phone}</span><div className="resource-foot"><StatusBadge status={expired ? 'UNAVAILABLE' : item.status}/><small>{expired ? 'Driver licence expired' : item.status === 'AVAILABLE' ? 'Licence valid' : 'Driver unavailable'}</small></div></button> })}</div><div className="wizard-tip"><ShieldAlert size={18}/> Drivers on a trip or with an expired licence are unavailable for new assignments.</div></>}
    {step === 3 && <><div className="wizard-title"><span>STEP 04 / 05</span><h3>Select a vehicle</h3><p>Choose a vehicle with enough capacity for the pickup.</p></div><div className="choice-grid two-col">{vehicles.map(item => { const enabled = item.status === 'AVAILABLE'; return <button key={item.vehicleId} disabled={!enabled} title={!enabled ? item.status === 'MAINTENANCE' ? 'Vehicle under maintenance' : 'Vehicle currently on a trip' : undefined} className={`choice-card resource-choice ${vehicleId === item.vehicleId ? 'selected' : ''}`} onClick={() => setVehicleId(item.vehicleId)}><div className="choice-card-top"><span className="choice-icon"><Truck size={20}/></span><span className="choice-check"><Check size={14}/></span></div><strong>{item.type}</strong><span>{item.registrationNumber} · {item.capacityKg} kg</span><div className="resource-foot"><StatusBadge status={item.status}/><small>{item.status === 'MAINTENANCE' ? 'Vehicle under maintenance' : item.status === 'ON TRIP' ? 'Currently on a trip' : 'Ready for pickup'}</small></div></button> })}</div></>}
    {step === 4 && <><div className="wizard-title"><span>STEP 05 / 05</span><h3>Review assignment</h3><p>Confirm the pickup details before creating the assignment.</p></div><div className="review-card"><div className="review-head"><span><CheckCircle2 size={20}/> Ready to schedule</span><strong>Food rescue pickup</strong></div><div className="review-grid"><div><span>Event</span><strong>{event.title}</strong><small><MapPin size={14}/>{event.location}</small></div><div><span>Volunteer / Team</span><strong>{team?.teamName ?? volunteer?.name}</strong><small><UsersRound size={14}/>{team ? `${team.memberIds.length} team members` : volunteer?.volunteerId}</small></div><div><span>Role</span><strong>{role}</strong></div><div><span>Driver</span><strong>{driver?.name}</strong><small>{driver?.phone}</small></div><div><span>Vehicle</span><strong>{vehicle?.type}</strong><small>{vehicle?.registrationNumber} · {vehicle?.capacityKg} kg</small></div><div><span>Pickup time</span><strong>{formatTime(event.dateTime)}</strong><small><CalendarDays size={14}/>{formatDate(event.dateTime)}</small></div></div></div><p className="review-note">This assignment will be added with a <strong>Pending</strong> status.</p></>}
  </div><div className="wizard-footer"><button className="button button-secondary" onClick={step === 0 ? onClose : () => setStep(step - 1)}>{step === 0 ? 'Cancel' : <><ArrowLeft size={17}/> Back</>}</button><div className="step-counter">Step {step + 1} of 5</div>{step === 4 ? <button className="button button-primary" onClick={create} disabled={submitting}>{submitting ? <><span className="button-spinner"/> Creating…</> : <><Check size={18}/> Create Assignment</>}</button> : <button className="button button-primary" onClick={goNext} disabled={!canNext}>Continue <ArrowRight size={17}/></button>}</div></div></Modal>
}
