import { ArrowRight, Crown, Plus, ShieldCheck, UserMinus, UserPlus, UsersRound } from 'lucide-react'
import { useState, type Dispatch, type SetStateAction } from 'react'
import type { Volunteer, VolunteerTeam } from '../types'
import { Avatar, Drawer, Modal, StatusBadge } from '../components/common/UI'

type Props = { volunteers: Volunteer[]; teams: VolunteerTeam[]; setTeams: Dispatch<SetStateAction<VolunteerTeam[]>>; onAssignTeam: (volunteerId: string, teamId: string) => void; notify: (message: string, kind?: 'success' | 'error') => void }

export default function Teams({ volunteers, teams, setTeams, onAssignTeam, notify }: Props) {
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [createOpen, setCreateOpen] = useState(false)
  const [teamName, setTeamName] = useState('')
  const [leaderId, setLeaderId] = useState('')
  const [memberPicker, setMemberPicker] = useState(false)
  const [leaderPicker, setLeaderPicker] = useState(false)
  const selected = teams.find(team => team.teamId === selectedId)
  const getVolunteer = (id: string) => volunteers.find(volunteer => volunteer.volunteerId === id)
  const createTeam = (event: React.FormEvent) => { event.preventDefault(); if (!teamName.trim() || !leaderId) { notify('Add a team name and select a leader.', 'error'); return }; if (teams.some(team => team.teamName.toLowerCase() === teamName.trim().toLowerCase())) { notify('A team with this name already exists.', 'error'); return }; const next = Math.max(0, ...teams.map(team => Number(team.teamId.slice(1)) || 0)) + 1; const teamId = `T${String(next).padStart(3,'0')}`; setTeams(current => [...current, { teamId, teamName:teamName.trim(), leaderId, memberIds:[leaderId] }]); onAssignTeam(leaderId, teamId); setCreateOpen(false); setTeamName(''); setLeaderId(''); notify('Team created successfully.') }
  const removeMember = (volunteerId: string) => { if (!selected) return; onAssignTeam(volunteerId, ''); notify('Team member removed.') }
  const changeLeader = (volunteerId: string) => { if (!selected) return; setTeams(current => current.map(team => team.teamId === selected.teamId ? { ...team, leaderId:volunteerId } : team)); setLeaderPicker(false); notify('Team leader updated.') }
  return <><div className="page-heading"><div><span className="eyebrow">PEOPLE WORKING TOGETHER</span><h1>Volunteer Teams</h1><p>Build reliable crews for every food rescue.</p></div><button className="button button-primary" onClick={() => setCreateOpen(true)}><Plus size={18}/> Create Team</button></div><div className="team-intro"><div className="team-intro-icon"><UsersRound size={23}/></div><div><strong>Stronger together</strong><p>Teams bring the right mix of people and skills to each pickup. Open a team to manage its members and leader.</p></div><span>{teams.length} active teams</span></div><div className="team-grid">{teams.map(team => { const members = team.memberIds.map(id => getVolunteer(id)).filter((member): member is Volunteer => !!member); const available = members.filter(member => member.status === 'AVAILABLE').length; const leader = getVolunteer(team.leaderId); return <article className="team-card" key={team.teamId}><div className="team-card-top"><div className="team-symbol"><UsersRound size={22}/></div><StatusBadge status={available ? 'AVAILABLE' : 'UNAVAILABLE'}/></div><div className="team-card-title"><span>{team.teamId}</span><h2>{team.teamName}</h2></div><div className="team-leader"><span>TEAM LEADER</span><div><Avatar name={leader?.name ?? 'Team leader'} size="sm"/><strong>{leader?.name ?? 'Unassigned'}</strong><Crown size={15}/></div></div><div className="team-card-stats"><div><strong>{members.length}</strong><span>Members</span></div><div><strong>{available}</strong><span>Available</span></div></div><div className="team-card-footer"><div className="avatar-stack">{members.slice(0,4).map(member => <Avatar key={member.volunteerId} name={member.name} size="sm"/>)}{members.length > 4 && <span className="avatar-overflow">+{members.length - 4}</span>}</div><button onClick={() => setSelectedId(team.teamId)}>View Team <ArrowRight size={17}/></button></div></article> })}</div>
    {selected && <Drawer title="Team details" onClose={() => { setSelectedId(null); setMemberPicker(false); setLeaderPicker(false) }}><div className="drawer-body"><div className="team-detail-hero"><div className="team-symbol"><UsersRound size={26}/></div><span>{selected.teamId}</span><h2>{selected.teamName}</h2><p>Coordinate membership and leadership for upcoming pickups.</p></div><div className="team-detail-summary"><div><span>Leader</span><strong>{getVolunteer(selected.leaderId)?.name ?? 'Unassigned'}</strong></div><div><span>Members</span><strong>{selected.memberIds.length}</strong></div><div><span>Available</span><strong>{selected.memberIds.filter(id => getVolunteer(id)?.status === 'AVAILABLE').length}</strong></div></div><div className="detail-section"><div className="section-heading"><h3>Team members</h3><button className="text-link" onClick={() => { setMemberPicker(!memberPicker); setLeaderPicker(false) }}><UserPlus size={16}/> Add member</button></div>{memberPicker && <div className="inline-picker"><label>Add a volunteer<select defaultValue="" onChange={e => { if (e.target.value) { onAssignTeam(e.target.value, selected.teamId); setMemberPicker(false); notify('Member added to team.') } }}><option value="" disabled>Select volunteer</option>{volunteers.filter(v => !selected.memberIds.includes(v.volunteerId)).map(volunteer => <option value={volunteer.volunteerId} key={volunteer.volunteerId}>{volunteer.name} · {volunteer.teamId ? 'Move from another team' : 'Unassigned'}</option>)}</select></label></div>}{selected.memberIds.map(id => { const member = getVolunteer(id); if (!member) return null; return <div className="member-row" key={id}><Avatar name={member.name}/><div><strong>{member.name}{id === selected.leaderId && <Crown size={14}/>}</strong><StatusBadge status={member.status}/></div>{id !== selected.leaderId && <button className="icon-button" title={`Remove ${member.name}`} aria-label={`Remove ${member.name}`} onClick={() => removeMember(id)}><UserMinus size={18}/></button>}</div> })}</div><div className="detail-section"><div className="section-heading"><h3>Leadership</h3></div><div className="leadership-note"><ShieldCheck size={20}/><span>A team leader is responsible for coordinating the crew at pickup.</span></div><button className="button button-secondary full-width" onClick={() => { setLeaderPicker(!leaderPicker); setMemberPicker(false) }}>Change Leader</button>{leaderPicker && <div className="leader-options">{selected.memberIds.filter(id => id !== selected.leaderId).map(id => <button key={id} onClick={() => changeLeader(id)}><Avatar name={getVolunteer(id)?.name ?? ''} size="sm"/>{getVolunteer(id)?.name}</button>)}{selected.memberIds.length < 2 && <p className="quiet-text">Add another member before changing the leader.</p>}</div>}</div></div></Drawer>}
    {createOpen && <Modal title="Create a team" subtitle="Start a new volunteer crew for Bengaluru pickups." onClose={() => setCreateOpen(false)}><form className="dialog-form" onSubmit={createTeam}><div className="form-grid"><label className="field field-full">Team name<input value={teamName} onChange={e => setTeamName(e.target.value)} placeholder="e.g. Team Echo" required/></label><label className="field field-full">Team leader<select value={leaderId} onChange={e => setLeaderId(e.target.value)} required><option value="">Select a volunteer</option>{volunteers.map(volunteer => <option value={volunteer.volunteerId} key={volunteer.volunteerId}>{volunteer.name}{volunteer.teamId ? ' · moves from current team' : ''}</option>)}</select></label></div><p className="form-note">You can add more members after creating the team.</p><div className="dialog-footer"><button type="button" className="button button-secondary" onClick={() => setCreateOpen(false)}>Cancel</button><button className="button button-primary" type="submit">Create Team</button></div></form></Modal>}
  </>
}
